# Generated by Django 6.1 on 2026-09-17 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0002_activitylog'),
        ('students', '0002_studentprofile_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='lecturers.lecturerprofile'),
        ),
    ]
