# Generated by Django 6.1 on 2026-09-28 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentprofile_must_change_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('tutorial', 'Tutorial'), ('assignment', 'Assignment'), ('major_project', 'Major Project')], max_length=30)),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_grade', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to='students.courseunit')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to='students.studentprofile')),
            ],
            options={
                'ordering': ['assessment_type'],
                'unique_together': {('student', 'course_unit', 'assessment_type')},
            },
        ),
    ]
