# Generated by Django 6.1 on 2026-09-28 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_gradebookentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradebookentry',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='gradebookentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gradebookentry',
            name='assessment_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gradebookentry',
            name='assessment_type',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='gradebookentry',
            name='final_grade',
        ),
        migrations.CreateModel(
            name='GradebookFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_grade', models.CharField(blank=True, max_length=10)),
                ('is_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='students.courseunit')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='students.studentprofile')),
            ],
            options={
                'ordering': ['course_unit__code'],
                'constraints': [models.UniqueConstraint(fields=('student', 'course_unit'), name='unique_student_course_final_grade')],
            },
        ),
    ]
