# Generated by Django 6.1 on 2026-09-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_gradebookentry_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gradebookfinal',
            name='unique_student_course_final_grade',
        ),
        migrations.AddField(
            model_name='gradebookentry',
            name='final_grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='gradebookentry',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='GradebookFinal',
        ),
    ]
