# Generated by Django 6.1 on 2026-09-02 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0003_rename_submmitted_at_assignmentsubmission_submitted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_grade', models.CharField(blank=True, max_length=10)),
                ('criterion_scores', models.JSONField(blank=True, default=dict)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('feedback', models.TextField(blank=True)),
                ('lecturer_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lecturer_feedback', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='assignments.assignmentsubmission')),
            ],
        ),
    ]
