# Generated by Django 6.1 on 2026-09-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='academic_writing_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assessment',
            name='citation_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assessment',
            name='grammar_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reference_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
