# Generated by Django 6.1 on 2026-08-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='markingguide',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
