# Generated by Django 6.1 on 2026-09-02 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignmentsubmission_extracted_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentsubmission',
            old_name='submmitted_at',
            new_name='submitted_at',
        ),
    ]
