# Generated by Django 6.1 on 2026-09-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0002_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
